### ISSUE TITLE
Use VBoxManage to detect VM start rather that screenshot parsing

### ISSUE THREAD

**Issue by dpogue** [vmactions/solaris-vm#15]
VirtualBox has some default properties that are exposed on guests, and VBoxManage includes a way to wait until a property is defined.

`VBoxManage guestproperty wait sol-11_4-vbox "/VirtualBox/GuestInfo/OS/NoLoggedInUsers"` seems to work to avoid the repeated looping/OCR here: https://github.com/vmactions/solaris-vm/blob/13811b4cde4b621079aa7a7d545e0e06d1924cb6/index.js#L167-L170

This probably doesn't lead to booting the VM any faster, but it should allow dropping the tesseract dependency and avoiding the brew install step.

**Comment by Neilpang** [comment]
>> https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/vboxmanage-guestproperty.html

It requires that: "provided that a guest is running and has the Guest Additions installed. "
