### ISSUE TITLE
Root CA public certs out of date

### ISSUE THREAD

**Issue by casesolved-co-uk** [vmactions/solaris-vm#16]
I'm getting curl error code 60 when communicating with a Let's Encrypt protected HTTPS website. Probably because of the change in Root CA in Sept 2021.

https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Solaris not listed here:
https://letsencrypt.org/docs/certificate-compatibility/

https://github.com/acmesh-official/acme.sh/pull/3849

**Comment by Neilpang** [comment]
fixed, please try again.
