### ISSUE TITLE
Solaris VM is no longer working

### ISSUE THREAD

**Issue by gansm** [vmactions/solaris-vm#18]
Your Solaris VM no longer works with any build. 

vboxmanage seems to have disappeared from the environment:

```
sudo: vboxmanage: command not found
Error: The process '/usr/bin/sudo' failed with exit code 1
```

See: https://github.com/gansm/finalcut/runs/4993570232?check_suite_focus=true

**Comment by Neilpang** [comment]
```
  runs-on: macos-10.15
```
