### ISSUE TITLE
No compiler installed?

### ISSUE THREAD

**Issue by mirabilos** [vmactions/solaris-vm#33]
cc: not found [No such file or directory]

**Comment by mirabilos** [comment]
mirabilos dixit:

>    cc: not found [No such file or directory]

Apparently, one can do:

https://github.com/mirabilos/mksh/commit/5c404e3d8f64faa2e8ea3529d56a9b22d8ea1091

Though no Sun compiler forthcoming. Still good to be able to test on
Slowlartus, at all.

bye,
//mirabilos
-- 
21:12⎜<Vutral> sogar bei opensolaris haben die von der community so
ziemlich jeden mist eingebaut │ man sollte unices nich so machen das
desktopuser zuviel intresse kriegen │ das macht die code base kaputt
21:13⎜<Vutral:#MirBSD> linux war früher auch mal besser :D

**Comment by Neilpang** [comment]
yes, the system was just installed with default configurations.

**Comment by wdlkmpx** [comment]
I tried to install gcc-7 but it's not there, but if you search solaris pkgs, you'll see many gcc versions, including gcc-7
http://pkg.oracle.com/solaris/release/en/index.shtml

Hmm it's using packages from OpenCSW, only gcc 4 & 5 available
https://www.opencsw.org/

so basically this installs the C & C++ compilers
`pkgutil -y -i gcc5core gcc5g++`

**Comment by mirabilos** [comment]
wdlkmpx dixit:

>so basically this installs the C & C++ compilers

Yeah, I have this…

            "prepare": "pkgutil -y -i gcc5core",

… added to my config for now, but ⓐ that’s only GCC, not the
“real” compiler on that OS, and ⓑ takes *ages* to install.

bye,
//mirabilos
-- 
[16:04:33] bkix: "veni vidi violini"
[16:04:45] bkix: "ich kam, sah und vergeigte"...

**Comment by wdlkmpx** [comment]
Yeah the first run (20 minutes), I realized that I have to use a certain gcc version
Then in the second run I had to wait like 30 minutes, it did install gcc and g++ only to fail with the Makefile (doesn't support  make -C) 

At this point I figured out I should install gmake, but I still haven't run the next job, it's too heavy a job

Overall, other compilers than gcc & clang are probably too buggy, so it's ok to test it with gcc or clang no matter the OS, clang is not available in OpenCSW, so gcc is the only option

**Comment by mirabilos** [comment]
wdlkmpx dixit:

>Overall, other compilers than gcc & clang are probably too buggy, so

Nope, SUNWcc works for me, normally.

**Comment by Neilpang** [comment]
https://github.com/vmactions/solaris-vm/issues/37
