### ISSUE TITLE
Illumos: OpenIndiana, OmniOS?

### ISSUE THREAD

**Issue by michalszmidt** [vmactions/solaris-vm#34]
As Solaris is discontinued by Oracle, how about adding support for continuation of them, that is Illumos?
Wikipedia says that [OpenIndiana](https://www.openindiana.org/) and [OmniOS](https://omnios.org) are current working distributions.

**Comment by Neustradamus** [comment]
To follow

**Comment by Neilpang** [comment]
OmniOs is supported:  https://github.com/vmactions/omnios-vm

I will check OpenIndiana soon.

**Comment by Neustradamus** [comment]
@Neilpang: Nice, good job!

Maybe you can see for:
- https://ghostbsd.org/
- https://midnightbsd.org/
- https://nomadbsd.org/
- https://www.haiku-os.org/
- https://reactos.org/
- https://github.com/PureDarwin/PureDarwin/wiki

**Comment by Neustradamus** [comment]
@Neilpang: Nice, good job!

Maybe you can see for:
- https://ghostbsd.org/
- https://midnightbsd.org/
- https://nomadbsd.org/
- https://www.haiku-os.org/
- https://www.puredarwin.org/
- https://reactos.org/

**Comment by Neilpang** [comment]
I think it's enough for now. unless there are other demands.

**Comment by michalszmidt** [comment]
@Neustradamus 
GhostBSD, MidnightBSD, NomadBSD are all FreeBSD based. 
They may have different user-spaces (but generally FreeBSD binaries with same ABI should work if I'm not wrong), but not that much, to be important.

I really like idea of PureDarwin however development is slow, and if I'm not wrong, some syscalls are not implemented, so this OS is not really in usable state. 
Also the working iso they provided is based on EOL version of darwin. 
All in all, I don't see any usage scenario.

@Neilpang 
I'm also interested in **Haiku**.

Also I'd propose some Zircon-based distro like [**FuschiaOS**](https://fuchsia.dev/) and **RedoxOS** that may positively impact software development for those small project.

Maybe also **ChromeOS**, despite it's gentoo-based, it has significantly different user-space.

**Comment by Neilpang** [comment]
haiku:  it's still  beta? 

Redox,  the iso can not install in kvm. just blocked. 

let's keep the current for now.  If there are other demands, we can review.
