### ISSUE TITLE
No output *during* job run; sometimes it doesn’t even work

### ISSUE THREAD

**Issue by mirabilos** [vmactions/solaris-vm#35]
I’ve had multiple times where a vm-solaris build timed out after a couple hours because it froze at some point (mostly during VM startup), which is very annoying.

But I also had the case where I killed a job after almost two hours of no output during job run, only to THEN get the output and it had *almost* finished building, so had I waited another two minutes it would have terminated by its own.

So please:
- make it so that the build log gets the output of the VM while it runs (this ought to be trivial when connecting to the VM via ssh or even telnet instead of using an emulated console)
- figure out why it sometimes doesn’t boot (maybe just another VBox issue that could be solved by switching to linux-kvm like for the vm-openbsd ones?)

**Comment by dbwiddis** [comment]
This seems similar to https://github.com/vmactions/freebsd-vm/issues/74 but openbsd seems to work.

**Comment by Neustradamus** [comment]
It is an important issue!

**Comment by mirabilos** [comment]
This probably works with the new libvirt/kvm/ssh-based system, closing.
